config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  	devise_scope :user do
  		root to: 'devise/sessions#new'
  	end
	get 'welcome', to: 'welcome#home' 
	get 'createtask', to: 'welcome#home' 
	post 'createtask', to: 'welcome#createTask'
	get 'viewtask', to: 'welcome#viewTask'
	get 'viewdata', to: 'welcome#viewData'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
	validates :task_title, :task_description, :presence => true
	validates :task_title, :task_description, :length => {:minimum => 5, :maximum => 50}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tasks
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

     protected
         def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
         end
         
  def after_sign_in_path_for(resource)
    welcome_url
  end

  def after_sign_out_path_for(resource)
    new_user_session_url
  end      
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	protected

	def after_sign_up_path_for(resource)
		welcome_url
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :custom_auth

	def custom_auth
		unless user_signed_in?
			redirect_to new_user_session_url
		end	
	end
	def home
	  	@errors={}
	  	p Task.joins(:user).select("tasks.task_title,users.name")
	end  	
	def createTask
		p params
		task = Task.new
		task.user_id = current_user.id
		task.task_title = params["task_title"]
		task.task_description = params["task_description"]
		task.save

		@errors =task.errors.messages
		p @errors
		render :home
	end
	def viewData
		respond_to do |format|
		   format.html
		   format.json { render json: TaskDatatable.new(params, user: current_user.id) }
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/_header.html.erb
<div class="row header">	
	<div class="col-sm-6">
		<h3>TODO Organiser</h3>
	</div>
	<div class="col-sm-6 headcont">
		<%="Welcome "+current_user.name%>&nbsp;&nbsp;&nbsp;&nbsp;
		<%=link_to("Logout", destroy_user_session_path, method: :delete)%>
	</div>
</div>

app/views/welcome/_tasks.html.erb
	<table id="tasks-datatable" class="table table-hover" data-source="<%= viewdata_path(format: :json) %>">
	  <thead>
	    <tr>
	      <th>No</th>
	      <th>Task Title</th>
	      <th>Created on</th>
	    </tr>
	  </thead>
	  <tbody>
	  </tbody>
	</table>

app/views/welcome/home.html.erb
<div class="container">
	<%= render "header" %>
	
	<div class="row">
		<div class="col-md-4">	
			<div class="box_bar">
		      Add new task
		    </div>
		    <div class="form_wrap">
			<%=form_tag(controller:'welcome',action:'createTask',method:'post') do %>	
				<div class="form-group">
					<%=label_tag(:task_title,"Task Title") %><br/>
					<%=text_field_tag(:task_title,"",class: 'form-control') %>
					<div class="error">
						<% if @errors.include?(:task_title) %>
							<%=@errors[:task_title][0] %>
						<% end %>	
					</div>
				</div>
				
				<div class="form-group">
					<%=label_tag(:task_description ,"Task Description") %><br/>
					<%=text_area_tag(:task_description,"",rows: "5",class: 'form-control') %>
					<div class="error">
						<% if @errors.include?(:task_description) %>
							<%=@errors[:task_description][0] %>
						<% end %>
					</div>
				</div>
				<div class="form-group">
					<%=submit_tag("Add task",class: "btn btn-secondary") %>
				</div>
				
			<% end %>
			</div>
		</div>
		<div class="col-md-8">
			<%= render "tasks" %>
		</div>
	</div>



</div>